title: Title
description: Stuff
url: "https://devPeri.github.io"
remote_theme: devPeri/millidocs

markdown: kramdown
highlighter: rouge
#kramdown:
#  syntax_highlighter_opts:
#    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
  
disable_search: true
disable-prism: true
