title: Title
description: Stuff
url: "https://devPeri.github.io"
remote_theme: devPeri/millidocs

highlighter: rouge

markdown: kramdown
#kramdown:
#  syntax_highlighter_opts:
#    disable : true
kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1     
      
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
  
disable_search: true
disable-milligram: true
disable-prism: true
