title: Title
description: Stuff
url: "https://devPeri.github.io"
remote_theme: devPeri/millidocs

markdown: kramdown
kramdown:
  input: GFM
    syntax_highlighter: coderay
    syntax_highlighter_opts:
      # Use existing pygments syntax highlighting css
      css_class: 'highlight'  
#  syntax_highlighter_opts:
#    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
  
disable_search: true
