title: Title
description: Stuff
url: "https://devPeri.github.io"
remote_theme: devPeri/millidocs

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
  
disable_search: true
